### ISSUE TITLE
Usar com o GPT4ALL

### ISSUE THREAD

**Issue by wilkensgomes** [DominguesM/alpaca-lora-ptbr-7b#2]
Fala Maicon, você tem ideia de como fazer esse teu modelo rodar no GPT4ALL ?

**Comment by DominguesM** [comment]
Olá @wilkensgomes , segue exemplo: https://colab.research.google.com/drive/1MDwDLzDZ66y-2JGyg0KDF3X8CTOIswUm?usp=sharing

**Comment by wilkensgomes** [comment]
Muito obrigado Maicon, sucesso irmão.
