### ISSUE TITLE
Link do binário não funciona mais

### ISSUE THREAD

**Issue by fjunqueira** [DominguesM/alpaca-lora-ptbr-7b#3]
Oi!! Estava querendo realizar alguns testes com a versão do modelo que havia sido disponibilizada aqui: https://nlprocks.s3.sa-east-1.amazonaws.com/alpaca/7B/alpaca-ptbr-7b.bin

Porém aparentemente o arquivo não existe mais.

Seria possível compartilhar ele novamente?

Obrigado! :)

**Comment by DominguesM** [comment]
Olá @fjunqueira, vou demorar um tempo para conseguir disponibilizar novamente, mas recomendo utilizar o modelo "Canarim", que seria uma versão melhor e mais completa do modelo.

Link para o modelo original: https://huggingface.co/dominguesm/canarim-7b
Link para o modelo no formato GGUF: https://huggingface.co/lucianosb/canarim-7B-GGUF
